<div class="bk_logo"><img src="images/bk_bottom.png" alt=""></div>
<div class="content">
    <div class="content_wrapper">
    <form action="save">
        <div class="wrapper">
            <div class="logo_convencion"><img src="images/logo_convencion.png" alt=""></div>
            <div class="title"><img src="images/title.png" alt=""></div>
            <div class="line"><img src="images/line.png" alt=""></div>
            <div class="home_text">
                ENCUESTA SATISFACCION CONVENCION COMERCIAL
            </div>
            <div class="content_register">
                <div class="header_content_register">FORMULARIO DE REGISTRO</div>
                <div class="content_info_register">                 
                    <div class="line_form">
                        <label for="">NOMBRE</label>
                        <input type="text" name="name">
                    </div>
                    <div class="line_form">
                        <label for="">CEDULA</label>
                        <input type="text" name="document" id="document">
                    </div>
                    <div class="content_btn_submit next_step">SIGUIENTE</div>                   
                </div>
            </div>
        </div><!--
        --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    Por favor marque en cada una de las casillas conforme a su percepción,  la calificación que considere pertinente a cada una de las variables tenidas en cuenta.
                </div>
                <div class="line_options">
                    <span>1.</span>  Solo para asistentes que llegaron a Bogotá vía aérea <br>
                    <p><span>a.</span> La logística de traslado aéreo sede-Bogotá-sede fue puntual y estuvo acorde a sus necesidades.</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="first_question" value="" class="value_check">
                    </div>
                </div>
                <div class="line_options">
                    <span>2.</span>  Invitación <br>
                    <p><span>a.</span> La invitación al evento le brindo información oportuna y clara acerca de fechas, lugares, vestuario y recomendaciones generales</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="second_question" value="" class="value_check">
                    </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    <span>3.</span>  Traslado Bogotá-Villavicencio-Bogotá <br>
                    <p><span>a.</span>   Los puntos de encuentro seleccionados fueron convenientes</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="third_question" value="" class="value_check">
                    </div>
                    <p><span>b.</span>   El manejo del equipaje durante el viaje hasta que fue retomado por usted en el hotel wyndham fue acertado.</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="four_question" value="" class="value_check">
                    </div>
                    <p><span>c.</span>   Los buses utilizados para el traslado hicieron seguro y confortable el viaje</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="five_question" value="" class="value_check">
                    </div>
                    <p><span>d.</span>   El sitio seleccionado para el desayuno fue adecuado</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="six_question" value="" class="value_check">
                    </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>                
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    <span>4.</span>  Actividades Outdoor <br>
                    <p>
                        <span>A.</span> Ruta Rio
                        <p class="sub_p">a. Fueron explicadas claramente las reglas del reto por los facilitadores</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="seven_question" value="" class="value_check">
                        </div>
                        <p class="sub_p"><span>b.</span> Generó cuestionamientos acerca del rol individual en línea con los planteamientos de la Mega 2-20-20</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="eigth_question" value="" class="value_check">
                        </div>
                        <p class="sub_p"><span>c.</span> Se hizo un cierre y reflexión adecuados para conectar las experiencias vividas en el rio Mega 2-20-20</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="nine_question" value="" class="value_check">
                        </div>
                    </p>
                    <p>
                        B. Mastermind (segundo día)
                        <p class="sub_p"><span>a.</span>  Fueron explicadas claramente las reglas de  por los facilitadores</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="ten_question" value="" class="value_check">
                        </div>
                        <p class="sub_p"><span>b.</span> Generó cuestionamientos acerca del rol individual en línea con los planteamientos de la Mega 2-20-20</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="eleven_question" value="" class="value_check">
                        </div>
                        <p class="sub_p"><span>c.</span> Se hizo un cierre y reflexión adecuados para conectar las experiencias vividas en el reto Mega 2-20-20</p>                        
                    </p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="twelve_question" value="" class="value_check">
                    </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    <span>5.</span>  Proceso check in/check out y habitaciones <br>
                        <p><span>a.</span>   Fue un proceso organizado y ágil</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="thirteen_question" value="" class="value_check">
                        </div>
                        <p><span>b.</span>   Se entregó información precisa acerca de los servicios incluidos en el paquete convención</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="fourteen_question" value="" class="value_check">
                        </div>
                        <p><span>c.</span>   Las habitaciones cumplían con sus expectativas de comodidad</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="fiveteen_question" value="" class="value_check">
                        </div>
                        <p><span>d.</span>   En el proceso de check out le  entregaron información ágil y clara acerca de sus cuenta y gastos adicionales</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="sixteen_question" value="" class="value_check">
                    </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    <span>6.</span>  Servicio Alimentos y Bebidas <br>
                        <p><span>a.</span>   El servicio prestado en los restaurantes del hotel fue ágil y oportuno</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="eigthteen_question" value="" class="value_check">
                        </div>
                        <p><span>b.</span>   Los menús seleccionados cumplieron la expectativa en cuanto a variedad y sabor</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="nineteen_question" value="" class="value_check">
                        </div>
                        <p><span>a.</span>   Los coffee breaks cumplieron la expectactiva en cuanto a variedad y sabor</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twenty_question" value="" class="value_check">
                        </div>
                        <p><span>d.</span>   Los stands con degustaciones de productos Alquería le parecieron adecuados</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="twentyone_question" value="" class="value_check">
                    </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    <span>7.</span>  Presentaciones y ayudas audiovisuales <br>
                        <p><span>a.</span>   La organización de la agenda y los horarios definidos estuvieron ajustados a sus expectativas</p>
                        <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentytwo_question" value="" class="value_check">
                        </div>
                            <p><span>b.</span>   Considera el sistema de interactivo (votación con control remoto)  una herramienta eficaz para evaluar los conocimientos grupales</p>
                            <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentythree_question" value="" class="value_check">
                        </div>
                            <p><span>c.</span>   Las presentaciones fueron concisas y claras y sus contenidos entregaron información relevante</p>
                            <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentyfour_question" value="" class="value_check">
                        </div>
                            <p><span>d.</span>   Los espacios abiertos para preguntas y respuestas generaron un ambiente de confianza para aclarar dudas y exponer ideas</p>
                            <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentyfive_question" value="" class="value_check">
                        </div>
                            <p><span>e.</span>   La organización de los grupos en círculos facilito las conversaciones entre los integrantes</p>
                            <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentysix_question" value="" class="value_check">
                        </div>
                            <p><span>f.</span>   El sonido y la ambientación facilitaron el desarrollo de las presentaciones</p>
                            <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentyseven_question" value="" class="value_check">
                        </div>
                        <p><span>g.</span>   Los videos presentados por los diferentes equipos le entregaron información relevante y deberían seguir siendo utilizados</p>
                        <div class="select_options">
                            <div class="select_options">
                            <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                            --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                            <input type="hidden" name="twentyeigth_question" value="" class="value_check">
                        </div>
                    </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                    <span>8.</span>  Actividades de Relacionamiento <br>
                        <p>La cena blanca, el show de magia y la fiesta de cierre generaron un espacio de intercambio e integración con colaboradores de otras regiones que antes no conocía</p>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="twentynine_question" value="" class="value_check">
                    </div>
                </div>
                <div class="line_options">
                    <span>9.</span>  La parece acertado tener dos días intensos de trabajo y un día de integración <br>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="thirty_question" value="" class="value_check">
                    </div>
                </div>
                <div class="line_options">
                    <span>10.</span> Regresaría al hotel o lo recomendaría o familiares o amigos <br>
                    <div class="select_options">
                        <div class="the_options first_question" attr="deactive" myvalue="Muy Bueno">Muy bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Bueno">Bueno</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Aceptable">Aceptable</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Regular">Regular</div><!--
                        --><div class="the_options first_question" attr="deactive" myvalue="Malo">Malo</div>
                        <input type="hidden" name="thirtyone_question" value="" class="value_check">
                    </div>
                </div>                
                <div class="final_button">COMPLETAR REGISTRO</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="form_final">
                    <div class="header_form_final">DATOS FINALES PARA COMPLETAR EL REGISTRO</div>
                    <div class="content_form_final">
                        <div class="congratulations">Felicidades! <span></span> <br>Te has registrado satisfactoriamente en nuestro portal</div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </div>  
</div>
<?php echo Tag::js('jquery/jquery.min');?>
<?php echo Tag::js('app/custom');?>