<div class="article">    
    <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="movie_name" align="middle">
    <param name="movie" value="swf/preloader.swf"/>
    <!--[if !IE]>-->

    <object type="application/x-shockwave-flash" data="swf/preloader.swf" width="100%" height="100%">
        <param name="movie" value="swf/preloader.swf"/>
        <param name="wmode" value="transparent"/>
    <!--<![endif]-->
        <a href="http://www.adobe.com/go/getflash">
            <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player"/>
        </a>
    <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
</object>

</div>
<div class="logo">
</div>