<div class="bk_logo"><img src="images/bk_bottom.png" alt=""></div>
<div class="content">
    <div class="content_wrapper">
    <form action="save">
        <div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
            <div class="line"><img src="images/line.png" alt=""></div>
            <div class="home_text">
                <img src="images/convencion-nacional.png" alt=""></div>
            </div>
                <div class="line_options">
                    Este registro nos ayudará a tener en cuenta información valiosa acerca de usted, la cuál usaremos en pro de su bienestar durante la convención .
                </div>
               
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">

                    <div class="item">
                            <p class="sub_p"><span>.</span>Nombre</p>
                            <div class="select_options">
                                <input type="text" name="name">
                            </div>
                        </div>

                    <div class="item">
                            <p class="sub_p"><span>.</span>Pasaporte</p>
                            <div class="select_options">
                                <input type="text" name="passport">
                            </div>
                        </div>
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>                
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                        <div class="item">
                            <p class="sub_p"><span>.</span>Tiene algún tipo de prescripción médica?</p>
                            <div class="select_options">
                                <div class="the_options first_question" attr="deactive" myvalue="Si">Si</div><!--
                                --><div class="the_options first_question" attr="deactive" myvalue="No">No</div>
                                <input type="hidden" name="first_question" value="" class="value_check">
                            </div>
                        </div>
                        <div class="item">
                             <p class="sub_p"><span>.</span>Ha tenido fracturas o lesiones serías recientemente?</p>
                                <div class="select_options">
                                    <div class="the_options second_question" attr="deactive" myvalue="Si">Si</div><!--
                                    --><div class="the_options second_question" attr="deactive" myvalue="No">No</div>
                                    <input type="hidden" name="second_question" value="" class="value_check">
                                </div>
                        </div>
                 <div class="item">
                             <p class="sub_p"><span>.</span>Tiene algún tipo de lesión que le imposibilite realizar esfuerzos físicos?</p>
                                <div class="select_options">
                                    <div class="the_options third_question" attr="deactive" myvalue="Si">Si</div><!--
                                    --><div class="the_options third_question" attr="deactive" myvalue="No">No</div>
                                    <input type="hidden" name="third_question" value="" class="value_check">
                                </div>
                        </div>
                 <div class="item">
                             <p class="sub_p"><span>.</span>Presenta alergia ante algún alimento, planta o animal?</p>
                                <div class="select_options">
                                    <div class="the_options fourth_question" attr="deactive" myvalue="Si">Si</div><!--
                                    --><div class="the_options fourth_question" attr="deactive" myvalue="No">No</div>
                                    <input type="hidden" name="fourth_question" value="" class="value_check">
                                </div>
                        </div>
                 <div class="item">
                             <p class="sub_p"><span>.</span>Considera que debe comunicarnos algo importante que debamos tener en cuenta para su bienestar?</p>
                                <div class="select_options">
                                    <div class="the_options fifth_question" attr="deactive" myvalue="Si">Si</div><!--
                                    --><div class="the_options fifth_question" attr="deactive" myvalue="No">No</div>
                                    <input type="hidden" name="fifth_question" value="" class="value_check">
                                </div>
                        </div>
                 
                </div>
                <div class="btn_next next_step second_step">SIGUIENTE</div>
            </div><!--
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="line_options">
                        <div class="item">
                            <p class="sub_p"><span>.</span>Persona Contacto en caso de emergencia</p>
                            <div class="select_options">
                                <input type="text" name="contact_emergency">
                            </div>
                        </div>
                        <div class="item">
                             <p class="sub_p"><span>.</span>Ciudad</p>
                                <div class="select_options">
                                    <input type="text" name="city">
                                </div>
                        </div>
                 <div class="item">
                             <p class="sub_p"><span>.</span>Teléfono Fijo</p>
                                <div class="select_options">
                                    <input type="text" name="phone">
                                </div>
                        </div>
                 <div class="item">
                             <p class="sub_p"><span>.</span>Teléfono Celular</p>
                                <div class="select_options">
                                    <input type="text" name="mobile">
                                </div>
                        </div>
                 
                </div>
                <div class="final_button">COMPLETAR REGISTRO</div>
            </div><!--
            
            
            --><div class="wrapper">
                <div class="logo2"><img src="images/logo2.png" alt=""></div>
                <div class="form_final">
                    <div class="content_form_final">
                        <div class="congratulations"><br><span></span><p>Se ha registrado exitosamente</p></div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </div>  
</div>
<?php echo Tag::js('jquery/jquery.min');?>
<?php echo Tag::js('app/custom');?>