<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="Expires" content="0">
		<meta http-equiv="Last-Modified" content="0">
		<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
		<meta http-equiv="Pragma" content="no-cache">
		<link href="favicon.ico" type="image/x-icon" rel="shortcut icon" />
        <title>Protagonistas de la Mega</title>
        <?php Tag::css('style') ?>
        <?php echo Html::includeCss() ?>
    </head>
    <body>
        <?php View::content(); ?>
    </body>
</html>